#ifndef GPH_MATH_CONFIG_H_
#define GPH_MATH_CONFIG_H_

#ifdef WIN32
/* this file is generated by cmake on windows */
#include "dllexport.h"
#else
#define GPH_MATH_API
#endif

#endif	/* GPH_MATH_CONFIG_H_ */
