#ifndef GPH_MATH_CONFIG_H_
#define GPH_MATH_CONFIG_H_

#ifdef _MSC_VER
/* this file is generated by cmake on windows, only needed with MSVC */
#include "dllexport.h"
#else
#define GPH_MATH_API
#endif

#endif	/* GPH_MATH_CONFIG_H_ */
